name: CI/CD Pipeline - Dependency Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *' # Executes daily at 3 AM

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update dependencies
        run: python update_dependencies.py

      - name: Run integration tests
        run: pytest tests/

      - name: Commit and Push (if tests pass)
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-name"
          git add requirements.txt

          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "Automatically update dependencies"
            git push
          else
            echo "No changes to commit."
          fi
        if: success()
